
ALTER TABLE public.sitters ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE public.sitters ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.sitters ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.sitters ADD COLUMN IF NOT EXISTS rating NUMERIC(3,2) NOT NULL DEFAULT 0;
ALTER TABLE public.sitters ADD COLUMN IF NOT EXISTS bookings_completed INTEGER NOT NULL DEFAULT 0;
