-- Add comprehensive filter columns to sitters
ALTER TABLE public.sitters
  ADD COLUMN IF NOT EXISTS drives boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_own_car boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS swims boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cooks boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS light_housework boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS homework_help boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS non_smoker boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS comfortable_with_pets boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS first_aid_certified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS police_cleared boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS newborn_experience boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS multiples_experience boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sen_experience boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS early_years_qualified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS teaching_qualified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS maternity_nurse boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS night_nanny boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS live_in_available boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS overnight_available boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS school_pickup boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS one_off_available boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS regular_available boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS video_intro_url text,
  ADD COLUMN IF NOT EXISTS age_groups text[] NOT NULL DEFAULT ARRAY[]::text[];
